#!/bin/bash
# CursorOS v3 - About

C='\033[38;5;39m'; W='\033[1;37m'; D='\033[38;5;245m'; G='\033[38;5;114m'; N='\033[0m'

echo ""
echo -e "${C}     ██████╗██╗   ██╗██████╗ ███████╗ ██████╗ ██████╗  ██████╗ ███████╗${N}"
echo -e "${C}    ██╔════╝██║   ██║██╔══██╗██╔════╝██╔═══██╗██╔══██╗██╔═══██╗██╔════╝${N}"
echo -e "${C}    ██║     ██║   ██║██████╔╝███████╗██║   ██║██████╔╝██║   ██║███████╗${N}"
echo -e "${C}    ██║     ██║   ██║██╔══██╗╚════██║██║   ██║██╔══██╗██║   ██║╚════██║${N}"
echo -e "${C}    ╚██████╗╚██████╔╝██║  ██║███████║╚██████╔╝██║  ██║╚██████╔╝███████║${N}"
echo -e "${C}     ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚══════╝${N}"
echo ""
echo -e "  ${W}CursorOS${N} v3.0.0 ${D}\"Horizon\"${N}"
echo -e "  ${D}A premium desktop operating system built with Cursor AI${N}"
echo ""
echo -e "  ${G}Based on${N}         Debian 12 (Bookworm)"
echo -e "  ${G}Desktop${N}          XFCE 4 + Plank Dock + Picom"
echo -e "  ${G}Theme${N}            WhiteSur Dark (macOS-inspired)"
echo -e "  ${G}Icons${N}            WhiteSur / Papirus"
echo -e "  ${G}Compositor${N}       Picom (shadows, transparency, rounded corners)"
echo -e "  ${G}Browser${N}          Firefox ESR"
echo -e "  ${G}Office${N}           LibreOffice"
echo -e "  ${G}Graphics${N}         GIMP, Inkscape"
echo -e "  ${G}Media${N}            VLC, Parole, Cheese"
echo -e "  ${G}Networking${N}       NetworkManager + Bluetooth"
echo -e "  ${G}Printing${N}         CUPS"
echo -e "  ${G}App Store${N}        GNOME Software + Flatpak"
echo -e "  ${G}AI Ready${N}         Ollama installer built-in"
echo ""
echo -e "  ${D}License: MIT${N}"
echo -e "  ${D}https://github.com/emailinuse804-png/emailinuse804-png.github.io${N}"
echo ""
